### ISSUE TITLE
'ConvexHull' object has no attribute 'faces'

### ISSUE THREAD

**Issue by bounceWei** [tengyu-liu/obb-from-mesh#1]
I wrote these code as follows, but I got a error: " 'ConvexHull' object has no attribute 'faces' ".
```
import numpy as np 
from scipy import spatial
from obb import get_bbox

np.random.seed(42)
point3d = np.random.rand(40,3)
hull = spatial.ConvexHull(point3d)
get_bbox(hull)
```

**Comment by tengyu-liu** [comment]
Sorry for the late reply. I hope this is still relevant. I used the `convex_hull` function from the `trimesh` library to compute the convex hull of a mesh, which returns a `trimesh.Trimesh` object with a `faces` attribute. Here's an example: 

```
import trimesh as tm
obj = tm.load('mesh.obj')
hull = obj.convex_hull()
obb = get_bbox(hull)
```
